"""Shell completion script generation.

Builds bash and zsh completion scripts straight from the live argument parser,
so the offered flags can never drift from the installed version's actual set.
"""

import argparse


def _completion_flags(
    parser: argparse.ArgumentParser,
) -> list[tuple[tuple[str, ...], str]]:
    """Return (option_strings, first help sentence) for every optional flag.

    Generated straight from the live parser, so the completion scripts below
    can never drift from the actual set of flags.
    """
    flags = []
    for action in parser._actions:
        if not action.option_strings:
            continue
        summary = (action.help or "").split(". ")[0].rstrip(".")
        flags.append((tuple(action.option_strings), summary))
    return flags


def bash_completion_script(parser: argparse.ArgumentParser) -> str:
    """Return a bash completion script offering every flag name."""
    words = " ".join(f for opts, _ in _completion_flags(parser) for f in opts)
    return (
        "# bash completion for certinspect - generated by "
        "`certinspect --print-completion bash`\n"
        "_certinspect_completion() {\n"
        '    local cur="${COMP_WORDS[COMP_CWORD]}"\n'
        f'    COMPREPLY=( $(compgen -W "{words}" -- "$cur") )\n'
        "}\n"
        "complete -F _certinspect_completion certinspect\n"
    )


def zsh_completion_script(parser: argparse.ArgumentParser) -> str:
    """Return a zsh completion script with each flag's help as its description."""
    lines = [
        "#compdef certinspect",
        "# generated by `certinspect --print-completion zsh`",
        "",
        "_certinspect() {",
        "  _arguments -s \\",
    ]
    for opts, summary in _completion_flags(parser):
        desc = summary.replace("'", "'\\''").replace("[", "(").replace("]", ")")
        spec = "{" + ",".join(opts) + "}" if len(opts) > 1 else opts[0]
        lines.append(f"    '{spec}[{desc}]' \\")
    lines.append("    '*::target:_default'")
    lines.append("}")
    lines.append("")
    lines.append('_certinspect "$@"')
    return "\n".join(lines) + "\n"
